### ISSUE TITLE
Create OpenZaak community videos

### ISSUE THREAD

**Issue by AlbaRoza** [publiccodenet/publiccode.net#117]
Videos featuring the community of OpenZaak.

To do:
- [x] ask community for participation on OpenZaak mailinglist
- [x] reach out to a minimum of participants
- [x] create basic script for contents
- [x] plan interviews
- [x] edit movies (x4)
- [x] publish on website

References [this issue](https://github.com/open-zaak/open-zaak-website/issues/38#issue-744620419).

**Comment by clausmullie** [comment]
@AlbaRoza Do I remember correctly this work was already done at some point?  I also checked the website, and these is a [new video](https://vimeo.com/389842983/4e46239132) on the OpenZaak homepage. Does that overlap with the intention of this video?

**Comment by AlbaRoza** [comment]
@clausmullie Hey Claus, thank you for pointing it out, I've seen it. I've decided I'm going to make individual videos of each contributor I got instead.

**Comment by Ainali** [comment]
I think we should add [the playlist](https://www.youtube.com/playlist?list=PL_5ziu2gADmCnEhBPf2KXXjGqaAdI3epJ) to the [OpenZaak overview page](https://publiccode.net/codebases/openzaak.html) (in the bottom of the community section).
It makes the pages look less similar since it deviates from the template, but it also add a lot of depth to it.

**Comment by clausmullie** [comment]
Closing this issue, as the original aim has been achieved. 

> I think we should add [the playlist](https://www.youtube.com/playlist?list=PL_5ziu2gADmCnEhBPf2KXXjGqaAdI3epJ) to the [OpenZaak overview page](https://publiccode.net/codebases/openzaak.html) (in the bottom of the community section). It makes the pages look less similar since it deviates from the template, but it also add a lot of depth to it.

This suggestion can be either done or rejected in #233
