### ISSUE TITLE
Add The Standard to the homepage under 'What we do'

### ISSUE THREAD

**Issue by 2045** [publiccodenet/publiccode.net#120]
On the homepage of the foundation, the Standard for Public code is not very present.
The landing page has 'What we do', 'Codebases we work with', 'Why we exist', 'Who we are', 'Come work with us' and the footer.

I can imagine that under 'What we do', apart from stewardship, the maintenance of the Standard for Public Code is mentioned as well, as this is quite a bit of important work that the foundation is doing...
With a direct link to the standard page.

**Comment by bvhme** [comment]
Thanks @2045! Seems important. :) 

I'm guessing this is on your backlog @ElenaFdR

**Comment by 2045** [comment]
A made a suggestion how to publish the subject on the home page, the pull request is there.. @ElenaFdR ..

**Comment by ElenaFdR** [comment]
Hi @2045! Thanks for the user feedback that this is important - #122 really shows how important you find it. @angelplasma and I are working on redesign of publiccode.net. We'll discuss this at our next meeting, and see how we can most quickly act on it.
(For example, one really quick action could be to create a new section for the Standard with an illustration, for example [community.svg](https://illustrations.publiccode.net/illustrations/community-2.svg)).

**Comment by ElenaFdR** [comment]
closed by #122.
