### ISSUE TITLE
Please consider posting the Standard for Public Code course on your website.

### ISSUE THREAD

**Issue by thijs-van-hm** [publiccodenet/publiccode.net#158]
The problem: I watched the trailer for your Standard for Public Code course on the website of CxC Academy, but if I want to see the rest of the course I have to sign up for an account. I hate signing up for accounts. I don't want to put my personal info on yet another US server just to be able to do the course!

The solution: maybe post the course on your website?

**Comment by Ainali** [comment]
This is sort of already solved. All text content in the course is already available in [the Standard for Public Code](https://standard.publiccode.net) itself. The only features added behind the login are videos summarizing the text, a few quizzes to check that you read it and the possibility to get a certificate (for which we need the name anyway). So for this specific introduction course there isn't more to get behind the login, but if we are adding an advanced course we should consider alternative ways of accessing it.

**Comment by ElenaFdR** [comment]
@thijs-van-hm Are you satisfied with @Ainali's response? Can I close this issue?

**Comment by thijs-van-hm** [comment]
Hi Elena,

Sure! Thanks for taking care.

Best,
Thijs
