### ISSUE TITLE
Add @2045's lovely testimonial

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/publiccode.net#173]
You may publish this:

"The foundation's code stewards helped us in a great way to make the step to maintaining our platform code fully open.
We had two sessions with code stewards enabling the team to determine the work to be done, making the step to working fully open.
Since some time the code is maintained at https://gitlab.com/logius/cloud-native-overheid where we work with more then one team on this code base.

A special thanks to Eric Herman and Jan Ainali
Martin Dias d'Ullois - Product Owner, Logius"

_Originally posted by @2045 in https://github.com/publiccodenet/publiccode.net/issues/70#issuecomment-781475244_

**Comment by ElenaFdR** [comment]
@2045, thank you for the very nice testimonial! I'd like to get it up promptly. I need 2 things from you to do so:

1. Our testimonial layout (for example [Jacco on the hompage](https://publiccode.net/) currently includes a photo - could you please provide us a headshot?
2. I've taken the liberty of shortening your quotation for layout reasons - please let me know if this ok, or if I've lost something essential?
> "The codebase stewards helped us in a great way to shift to maintaining our platform code fully in the open. We had two sessions with the stewards, enabling the team to determine the work to be done, then actually making the step to fully open work. We now work with more than one team on [the codebase on Gitlab](https://gitlab.com/logius/cloud-native-overheid)."

**Comment by 2045** [comment]
@ElenaFdR HI Elena, the shortening is fine by me.. pity the special thanks had to go... :( but I trust your judgement. Regarding a photo .. I kinda avoid having my face on the net.. so if we can avoid it, I would be great. Let me know if you can work without one, if not, i'll see if i can arrange for a Warhol style kinda pic (currently on holiday, would be able to produce one next week..)
