### ISSUE TITLE
Write a steward job advert with a policy focus

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/publiccode.net#189]
For the Careers page (and use elsewhere)

**Comment by clausmullie** [comment]
I am closing this page for now, as this is currently not a priority for hiring. We can reopen in January once the hiring strategy is defined (as per item 9 of the [board minutes](https://github.com/publiccodenet/about/blob/develop/organization/board-of-directors-meetings/2021-11-30-minutes.md))
