### ISSUE TITLE
Add Alphen aan de Rijn as a new replicator to Signalen overview page

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/publiccode.net#194]
Based on community news update.

**Comment by Ainali** [comment]
As far as I know, they have made the formal decision, but not really replicated it yet. Hopefully it won't take too long though!

**Comment by ElenaFdR** [comment]
Would adding them to 'scaling potential' make sense?

**Comment by Ainali** [comment]
Yes, for sure!
