### ISSUE TITLE
Add Kehinde to team

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/publiccode.net#212]
Add a bio and an image in the team folder.

**Comment by brandmuse** [comment]
Still awaiting my staff status.
I'm officially not a staff member.
That's why this is pending

**Comment by clausmullie** [comment]
Once this moves forward, this should also be updated on [About](https://github.com/publiccodenet/about/blob/develop/organization/staff.md)

**Comment by brandmuse** [comment]
Kehinde Bademosi is a storytelling strategist with over two decades of combined expertise in copywriting, service design, content marketing, and creative leadership spanning Africa, Europe, and the US
![kehinde bademosi](https://user-images.githubusercontent.com/89196490/148751480-1c3a849d-87e3-4a65-b47c-68ce62b6d730.jpg)
A
