### ISSUE TITLE
Leaflet has lorem ipsum texts left

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/publiccode.net#215]
Page 29 and 36 of [the leaflet](https://publiccode.net/case-support.pdf) still has lorem ipsum blurbs (also reported [on Twitter](https://twitter.com/btyga/status/1460539346243706880)).
Did we ever get any usable quotes? 
If not, should we just put some illustrations there instead until we have some?

**Comment by angelplasma** [comment]
@Ainali Hmmm... That was a very early, work-in-progress PDF. Not necessarily meant to be public, but certainly not to be presented as final.

The final PDF (which was also used in fundraising meetings) was eventually posted here: https://about.publiccode.net/activities/philanthropic-fundraising/

Is that old version actually linked to from a webpage, or did someone dig into a repo and find a file possibly used as internal reference? I'm guessing it become public by accident, and hope (/assume) it was not presented as something final...

**Comment by Ainali** [comment]
Yes, the old version is linked. But then the correct fix is to change the link to the right file and remove the old file. I can do that! Thanks for the update!

**Comment by angelplasma** [comment]
Oh weird. From where was it linked? I'm not sure why it would have been published (in #185 it seems?), but thank you for fixing, in any case!

**Comment by Ainali** [comment]
It's linked in the third paragraph on index.html "Only have a minute? Get to know us through this leaflet"

**Comment by angelplasma** [comment]
Whaaat. I feel like I'm in a weird alternate dimension. I don't understand how I missed that this was added 5 months ago... and I can't imagine that any combination of Alba/Boris/Elena would have meant to push that old PDF live.
