### ISSUE TITLE
Add back pages for former staff members

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/publiccode.net#239]
When thinking on publiccodenet/about#1115 we realized that it adds value to have URLs for our former team members not becoming 404 errors, but while still being clear that they are not longer employees at the organization. 
For example, it is plausible that they have used it in communications on other sites, like conferences or in blogs, and that there could be a considerable number of such links in the wild. If someone tries a URL like that, it would be better if they came to a page that said something like

> X was an employee 20XX to 20YY. You can find [our current team here](team.md).

rather than coming to a "Page not found", which makes the link, and our site (by association), to look sketchier than it is.

**Comment by bvhme** [comment]
I suggest for now we add a page with a list of former team members and link to with `redirect_from` headers.
