### ISSUE TITLE
responsible disclosure

### ISSUE THREAD

**Issue by MirjamvT** [publiccodenet/publiccode.net#25]
We should add this to our site

**Comment by bvhme** [comment]
We can add a bit about that emails can be sent to <security@publiccode.net> for which there is a process.

**Comment by clausmullie** [comment]
There is a responsible disclosure section on about, bottom of the [individual contributor page](https://about.publiccode.net/contributor-guides/for-individuals.html). I think this is enough to address the intent of this issue. 

There may be a better place for this section, but I am closing the issue for now.
