### ISSUE TITLE
Should the team pages have contact info?

### ISSUE THREAD

**Issue by ericherman** [publiccodenet/publiccode.net#291]
To reach out to a member of a team, it would be useful to have some sort of contact info, perhaps the work email address.

**Comment by ericherman** [comment]
If I compare https://publiccode.net/who-we-are/team/ben-cerveny.html to https://github.com/nebster , it seems clear that this would be valuable in at least some cases.

Depending upon the person and the role, perhaps a group/team email address might be best, this can be decided on a case-by-case basis.

**Comment by Ainali** [comment]
Yes, I think we should add some way to contact, and an email seems like the most obvious option. Whether it is our personal or a function one, like `codebasestewards` I don't think it matters much, but I lean towards the personal one.
