### ISSUE TITLE
Add call to action for partners 

### ISSUE THREAD

**Issue by clausmullie** [publiccodenet/publiccode.net#293]
Reflecting our change in direction, we have removed members from the home page. We should add a call to action for partners to get involved.

**Comment by Ainali** [comment]
Agreed. And I think the current Join us link in the header could be used for main navigation to get to a page like that. That page could have information about partners and affiliates as main content and possibly a link to careers and a section about philanthropic donations too.

**Comment by clausmullie** [comment]
Closing this for now, may be reconsidered in future work
