### ISSUE TITLE
Idea for nifty URLs

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/publiccode.net#50]
We could make the URLs for the main sections of these pages a bit easier. Since most of them already are starting with the question words, we could go for those which will be very easy to memorise. For example: 
* **codebase stewardship** would get https://publiccode.net/what 
* **background** would get https://publiccode.net/why
* **team** would get https://publiccode.net/who
* and in the future the codebases we steward can be shown on https://publiccode.net/which

**Comment by ElenaFdR** [comment]
Update: I plan to start work on this today.

**Comment by bvhme** [comment]
I think URLs should be descriptive of their content and I think the 4 W's, although poetically beautiful, are way too abstract. So if we're changing them, I feel we should change them in the opposite direction.

**Comment by ElenaFdR** [comment]
I tried to implemented this as a draft in #57, but received feedback from various people that this was confusing or contrived (not all of it on the Github issue).
I'm going to close this for now, but we can revisit it after #64 (and further design changes) to see if this is still desirable.
