### ISSUE TITLE
Rename repository?

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/publiccode.net#51]
**http** is a strange name that doesn't give much of a clue of the contents of it. Can we rename it to something more describing? Candidates could be **marketing site** that we use internally sometimes and **publiccode.net** seems pretty self describing. There are probably other candidates as well that could be better than http. Thoughts?

**Comment by ElenaFdR** [comment]
IIRC, we've discussed 'orientation', 'overview' and 'introduction' as well. 
@nebster also has strong opinions about this!

**Comment by bvhme** [comment]
I'd like to add 'home' or 'homepage' to the pile.

**Comment by clausmullie** [comment]
+1 home

**Comment by Ainali** [comment]
Home feels a bit non-descriptive and homepage reminds me of the old homepage/website debate (which in [Wikipedia](https://en.wikipedia.org/wiki/Home_page) has been resolved a long time ago, and where (usually) index.html of a website is its homepage). 
Looking around a little bit, it seems like other orgs are using the domain name as the name of the repository.

**Comment by bvhme** [comment]
Okay, I would vote renaming it to `publiccode.net` then. I like something descriptive and not too abstract.

**Comment by bvhme** [comment]
Also I would like to propose an artifical deadline for merging this change. I propose I'll change the name of this repository on Friday 3 April at 1100 to our decision.

And working by lazy consensus, if no alternative gets more traction, the name it'll be changed to is `publiccode.net`.

**Comment by bvhme** [comment]
The repo has now be renamed `publiccode.net`, update your bookmarks :)
