### ISSUE TITLE
Create a membership showcase highlights on our mainpage page and membership page

### ISSUE THREAD

**Issue by felixfaassen** [publiccodenet/publiccode.net#61]
I think it is really important that potential interested members or codebases immediately see who our members are and which codebases we have under stewardship. Nice black and white logo of the organisations with a brief summary, when clicking on it come to a member dedicated page which includes some basic info about the organisation and the codebases we have under stewardship.

Under each of this member showcase page we could at a link to the page explaining membership etc.

I

**Comment by clausmullie** [comment]
I feel this can be closed. We have a codebase page, and other issues open for a members page (#78 and #65) as well as pull request #106
