### ISSUE TITLE
Add publiccode.net/members

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/publiccode.net#65]
Publish as soon as we have permission

#61 includes suggestions for how to present members.

**Comment by ElenaFdR** [comment]
@Ainali suggestion: After members join, we should link to their political decisions to do so

**Comment by ElenaFdR** [comment]
This is partially fixed by [About repo PR 859](https://github.com/publiccodenet/about/pull/859).

**Comment by clausmullie** [comment]
Duplicates #78

**Comment by clausmullie** [comment]
Adding a bit of context as I was a bit confused when looking at this issue - this is similar to #78, but different. 

This is an issue for adding our existing members. #78 is an issue for adding information about membership and how to become a member. 

Both are adressed via #106

**Comment by clausmullie** [comment]
Closing this issue as members are no longer a priority
