### ISSUE TITLE
Idea: build a toolkit to get membership approval from your boss!

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/publiccode.net#71]
Here's a nice example of a [pre-packaged persuasion toolkit](https://go.govloop.com/2020-approval-toolkit).

**Comment by ElenaFdR** [comment]
Guessing at potential content.

What to do:
- top level talking points: why this is necessary for your successful digital transformation, concrete membership benefits for your organization
- how to help your org become a member (which decisionmakers are usually needed to support an org's membership)

Materials to persuade specific decisionmakers:

- business cases and why this makes financial sense
- absence of legal obstacles (could include links to national level reviews, like [OS2's Danish note](https://joinup.ec.europa.eu/collection/open-source-observatory-osor/news/balancing-all-duties)
- relevant encouraging policy frameworks (About repo issues [716](https://github.com/publiccodenet/about/issues/716), [630](https://github.com/publiccodenet/about/issues/630) and [572](https://github.com/publiccodenet/about/issues/572), including links to other countries' national FOSS catalogues
- case studies: successful Foundation for Public Code membership and FOSS adoption in other places! Ideally ones produced by the org/place in question, published on their own channels
- how to get started within your org: [New America Open Source in Government report](https://www.newamerica.org/digital-impact-governance-initiative/reports/building-and-reusing-open-source-tools-government/), OSOR report, [Linux Foundation guide to open source for procurement experts](https://www.linuxfoundation.org/blog/2020/04/a-guide-to-open-source-software-for-procurement-professionals/)

**Comment by ElenaFdR** [comment]
@nebster likes the idea of having publiccode.net/bibliograpy (or similar) would be cool to have on a slide near the end of a talk.

**Comment by ElenaFdR** [comment]
Draft content: https://hackmd.io/_QGMKrZvTyGe6XZJj7AzqA

**Comment by clausmullie** [comment]
Closing this issue as members are no longer a priority
