### ISSUE TITLE
Create publiccode.net/membership

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/publiccode.net#78]
Replace current call to action for potential members to email with specific persuasive content for decisionmakers at potential member orgs.
This may contain all of #71, depending on whether there's evidence these are the same users or not.

Category: public, generic
(from communications assets for membership workshop, 23 July 2020)

**Comment by lscheske** [comment]
@ElenaFdR, what is the current call to action? Is it the content under "join us" on publiccode.net?

Does replace with an email mean we are getting rid of that page all together?

**Comment by clausmullie** [comment]
Duplicates #65

**Comment by clausmullie** [comment]
This is addressed via #106

**Comment by clausmullie** [comment]
Adding a bit of context as I was a bit confused when looking at this issue - this is similar to #65, but different. 

#65 is an issue for adding our existing members. This is an issue for adding information about membership and how to become a member. 

Both are adressed via #106

**Comment by clausmullie** [comment]
Closing this issue as members are no longer a priority
