### ISSUE TITLE
Refresh publiccode.net/codebase-stewardship ⭐

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/publiccode.net#80]
This page is quite out of date. It should reflect what we're currently doing and where we've learned we add the most value (governance, community process improvement and risk mitigation?)

Users:
- general public
- Foundation people often use this page with potential members at the opportunity stage

From: communications assets for membership workshop, 23 July 2020
Prioritized during dotvoting.

**Comment by clausmullie** [comment]
Closed with #180. Can no doubt be refreshed again, but will close this for now until we decide this is a priority again.
