### ISSUE TITLE
Create overview pages for each codebase we work on ⭐⭐

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/publiccode.net#84]
These should set out:
- info about the codebase and what it does
- how we're helping/the value we provide
- the opportunity we see for the codebase
- how to get involved with the codebase!

From: communications assets for membership workshop, 23 July 2020
Prioritized during dotvoting.

**Comment by ElenaFdR** [comment]
I found [Helsinki's project page](https://dev.hel.ninja/projects/) inspirational, but it's now deprecated. It's been replaced by [very clear developer documentation](https://dev.hel.fi/).
Suggestion: informal user research to see if anyone finds these pages useful. Analytics tracking on where people go next from these pages would also be great.

**Comment by ElenaFdR** [comment]
This content has already been created for Signalen and OpenZaak as part of #64.

**Comment by lscheske** [comment]
> Suggestion: do user research to see if anyone finds these pages useful. Add analytics tracking to see where people go next from these pages.

I think analytics tracking is a separate thing that we need a decision on. If this is hampering your work currently, please let me know and we can find a way to get something up and running.
