### ISSUE TITLE
Case for Membership ⭐⭐

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/publiccode.net#88]
A downloadable PDF or leave behind material that helps people in an org argue for membership with others in their org.
Contents:
- explains what we do
- how it works
- why
- advantages

As much as possible, this will use stats, risk analysis - facts to persuade non-idealists.

Users:
- the general public
- fans at public organizations (#71)

Prioritized during dotvoting at communications assets for membership workshop, 23 July 2020.

**Comment by ElenaFdR** [comment]
Partial overlap: #69.

**Comment by lscheske** [comment]
This should be content pulled from the website, so I would prioritise getting it all up there first.
