### ISSUE TITLE
Create functionality to embed videos on publiccode.net

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/publiccode.net#90]
Use case: it'd be lovely to embed the [Signalen video](https://www.youtube.com/watch?v=I2Z-mRFt3pg&feature=youtu.be) (hosted on YouTube) on the Signalen overview page.

Here's a way to do this: https://github.com/nathancy/jekyll-embed-video

**Comment by ElenaFdR** [comment]
Issues #82 and #83 will also require this.

**Comment by bvhme** [comment]
You should be able to use the HTML embed directly inline as well.

**Comment by bvhme** [comment]
My previous comment should be the resolution to this issue. Re-open it if it doesn't work.
